return {
  settings = {
    intelephense = {
      stubs = {
        'memcache',
        'mongodb',
        'amqp',
        'redis',
        'bcmath',
        'bz2',
        'calendar',
        'Core',
        'ctype',
        'curl',
        'date',
        'dba',
        'dom',
        'enchant',
        'exif',
        'fileinfo',
        'filter',
        'ftp',
        'fpm',
        'frankenphp',
        'gd',
        'gettext',
        'gmp',
        'hash',
        'iconv',
        'imap',
        'intl',
        'json',
        'ldap',
        'libxml',
        'memcache',
        'mbstring',
        'mcrypt',
        'meta',
        'mysqli',
        'oci8',
        'odbc',
        'openssl',
        'pcntl',
        'pcre',
        'PDO',
        'pdo_ibm',
        'pdo_mysql',
        'pdo_pgsql',
        'pdo_sqlite',
        'pgsql',
        'Phar',
        'posix',
        'pspell',
        'random',
        'readline',
        'recode',
        'Reflection',
        'session',
        'shmop',
        'SimpleXML',
        'snmp',
        'soap',
        'sockets',
        'sodium',
        'SPL',
        'sqlite3',
        'standard',
        'superglobals',
        'sysvmsg',
        'sysvsem',
        'sysvshm',
        'tidy',
        'tokenizer',
        'wddx',
        'xdebug',
        'xml',
        'xmlreader',
        'xmlrpc',
        'xmlwriter',
        'Zend OPcache',
        'zip',
        'zlib',
      },
      compatibility = {
        preferPsalmPhpstanPrefixedAnnotations = true,
      },
      environment = {
        includePaths = { './vendor/**' },
        phpVersion = '8.4.0',
      },
      format = { enable = true },
      diagnostics = { enable = true },
    },
  },
}
